"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var config_1 = require("../configuration/config");
exports.setConfiguration = config_1.setConfiguration;
var assignImportedComponents_1 = require("../loadable/assignImportedComponents");
exports.assignImportedComponents = assignImportedComponents_1.assignImportedComponents;
var loadByChunkName_1 = require("../loadable/loadByChunkName");
exports.loadByChunkname = loadByChunkName_1.loadByChunkname;
var marks_1 = require("../loadable/marks");
exports.rehydrateMarks = marks_1.rehydrateMarks;
var pending_1 = require("../loadable/pending");
exports.whenComponentsReady = pending_1.done;
var preloaders_1 = require("../loadable/preloaders");
exports.addPreloader = preloaders_1.addPreloader;
var globalTracker_1 = require("../trackers/globalTracker");
exports.injectLoadableTracker = globalTracker_1.injectLoadableTracker;
